name: Download and Install Fortanix KMS Client

on:
  workflow_dispatch:

jobs:
  download-and-install:
    runs-on: windows-latest
    steps:
      - name: Download FortanixKmsClient.msi
        env:
          FORTANIX_USER: ${{ secrets.FORTANIX_USERNAME }}
          FORTANIX_PASS: ${{ secrets.FORTANIX_PASSWORD }}
        run: |
          $url = "https://download.fortanix.com/clients/5.1.2830/FortanixKmsClient-5.1.2830.msi"
          $output = "FortanixKmsClient-5.1.2830.msi"
          $pair = "$env:FORTANIX_USER`:$env:FORTANIX_PASS"
          $bytes = [System.Text.Encoding]::UTF8.GetBytes($pair)
          $encoded = [Convert]::ToBase64String($bytes)
          $headers = @{Authorization = "Basic $encoded"}
          Invoke-WebRequest -Uri $url -Headers $headers -OutFile $output

      - name: Install FortanixKmsClient.msi
        run: |
          Start-Process msiexec.exe -ArgumentList "/i FortanixKmsClient-5.1.2830.msi /qn /norestart" -Wait
        continue-on-error: true

      - name: Check FortanixKmsClientConfig.exe existence
        shell: pwsh
        run: |
          if (Test-Path "C:\Program Files\Fortanix\KmsClient\FortanixKmsClientConfig.exe") {
            Write-Host "FortanixKmsClientConfig.exe exists."
          } else {
            Write-Host "FortanixKmsClientConfig.exe NOT found."
            exit 1
          }

      - name: Verify Installation
        id: verify
        run: |
          $exists = Test-Path "C:\Program Files\Fortanix\KmsClient\"
          if ($exists) {
            echo "status=success" >> $env:GITHUB_OUTPUT
            Write-Host "Fortanix KMS Client installation succeeded."
          } else {
            echo "status=failure" >> $env:GITHUB_OUTPUT
            Write-Host "Fortanix KMS Client installation failed."
          }

      - name: Report Installation Status
        run: |
         if ("${{ steps.verify.outputs.status }}" -eq "success") {
         Write-Host "✅ Fortanix KMS Client installed successfully."
         } else {
         Write-Host "❌ Fortanix KMS Client installation failed."
         exit 1
         }
